name: PR Sync
description: "Argocd PR Sync"
inputs:
  git-sha:
    description: "Git short sha"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: pr-sync
      run: |
        sudo snap install yq
        export GITSHA=${{ inputs.git-sha }}
        yq eval -i 'del( .app.versions[] | select(.version == env(VERSION)) )' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i '.app.versions |= . + "{version: '${VERSION}', gitSha: '${GITSHA}'}"' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git add .
        git commit -m "Deploy ${HOST}.${{ inputs.env }}.aepps.com"
      shell: bash
