name: PR Sync
description: "Argocd PR Sync"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  git-sha:
    description: "Git short sha"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: pr-sync
      run: |
        sudo snap install yq
        export GITSHA=${{ inputs.git-sha }}
        export VERSION=${{ inputs.url-prefix }}
        export HOST=${{ inputs.url-prefix }}-${{ env.APP }}
        yq eval -i 'del( .app.versions[] | select(.version == env(VERSION)) )' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        sed -i "s/[][]//g" ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i '.app.versions |= . + ["{version: '${VERSION}', gitSha: '${GITSHA}'}"'] ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        sed -i "s/'//g" ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i '( . | .app.versions.[].version style="double")' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i '( . | .app.versions.[].gitSha style="double")' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config --local user.email "aeternity-bot@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Deploy ${HOST}.${{ inputs.env }}.service.aepps.com - commit id : ${GITSHA}"
      shell: bash
