name: Deploy HTTP Status
description: "Deploy HTTP Status"

branding:
  icon: server
  color: green

inputs:
  url:
    description: "Deployment URL"
    required: true
  timeout:
    description: "Timeout in seconds"
    required: false
    default: "300"
  interval:
    description: "Interval between checks in seconds"
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - id: deploy-status
      run: |
        LRED="\033[1;31m"   # Light Red
        LGREEN="\033[1;32m" # Light Green
        NC='\033[0m'        # No Color

        URL="${{ inputs.url }}"
        TIMEOUT=${{ inputs.timeout }}
        INTERVAL=${{ inputs.interval }}
        SECONDS_WAITED=0
        END=$((SECONDS + TIMEOUT))

        while [ $SECONDS -lt $END ]; do
          status_code=$(curl --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null "$URL")
          echo "HTTP Status Code: $status_code"
          if [ "$status_code" -eq 200 ] || [ "$status_code" -eq 301 ]; then
            echo -e "\n${LGREEN}The $URL deployment is OK. Status: $status_code. Proceed with the PR sync step!${NC}"
            exit 0
          fi
          echo -e "\n${LRED}Waiting for URL to be available... ($SECONDS_WAITED/$TIMEOUT seconds)${NC}"
          sleep $INTERVAL
          SECONDS_WAITED=$((SECONDS_WAITED + INTERVAL))
        done

        echo -e "\n${LRED}Timed out waiting for URL to be available. The deployment for $URL is missing, please fix it and then try to sync with new commits!${NC}"
        exit 1
      shell: bash
