name: Staging Deploy
description: "Staging Deploy"
inputs:
  url-prefix:
    description: "PR Number"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Deployed Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export VERSION=${{ inputs.url-prefix }}
        export HOST=${{ inputs.url-prefix }}-${{ env.APP }}
        yq eval -i 'del( .app.versions[] | select(. == env(VERSION))  )' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i 'del(... | select(.[] == "'${HOST}.${{ inputs.env }}.aepps.com'"))' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Uneploy ${VERSION}.${{ inputs.env }}.aepps.com"
      shell: bash
