name: Staging Deploy
description: "Staging Deploy"
inputs:
  pr-number:
    description: "PR Number"
    required: true
  env:
    description: "Environment"
    required: true
  argocd-file:
    description: "Argocd values file"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export URL_PREFIX=${{ inputs.url-prefix }}
        yq eval -i 'del( .app.versions[] | select(. == env(URL_PREFIX))  )' superhero-ui/${{ inputs.argocd-file }}
        yq eval -i 'del(... | select(.[] == "'${URL_PREFIX}.${{ inputs.env }}.aepps.com'"))' superhero-ui/${{ inputs.argocd-file }}
        cat superhero-ui/${{ inputs.argocd-file }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Uneploy pr-${URL_PREFIX}.${{ inputs.env }}.aepps.com"
      shell: bash
