name: Staging Deploy
description: "Staging Deploy"
inputs:
  pr-number:
    description: "PR Number"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Deployed Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export URL_PREFIX=${{ inputs.url-prefix }}
        yq eval -i 'del( .app.versions[] | select(. == env(URL_PREFIX))  )' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i 'del(... | select(.[] == "'${URL_PREFIX}.${{ inputs.env }}.aepps.com'"))' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Uneploy pr-${URL_PREFIX}.${{ inputs.app }}.${{ inputs.env }}.aepps.com"
      shell: bash
