name: Undeploy
description: "Argocd Undeploy"
inputs:
  url-prefix:
    description: "PR Number"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: undeploy
      run: |
        sudo snap install yq
        export VERSION=${{ inputs.url-prefix }}
        export HOST=${{ inputs.url-prefix }}-${{ env.APP }}
        yq eval -i 'del( .app.versions[] | select(.version == env(VERSION)) )' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        yq eval -i 'del( .app.ingress.hosts[] | select(.[] == "'${HOST}.${{ inputs.env }}.service.aepps.com'"))' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config user.name "github-actions"
        git config user.email "aeternity-bot@users.noreply.github.com"
        git add .
        git commit -m "Uneploy ${VERSION}.${{ inputs.env }}.service.aepps.com"
      shell: bash
