name: Deploy
description: "Argocd Deploy"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Application"
    required: true
  git-sha:
    description: "Git commit sha"
  domain:
    description: "Domain"
    required: false
    default: "service.aepps.com"
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export GITSHA=${{ inputs.git-sha }}
        export VERSION=${{ inputs.url-prefix }}

        if [ "${{ env.APP }}" == "hexpulse" ]; then
          export HOST=${{ inputs.url-prefix }}
        else
          export HOST=${{ inputs.url-prefix }}-${{ env.APP }}
        fi

        export DOMAIN=${{ inputs.domain }}
        
        if [ ${{ inputs.env }}  != "prd" ]; then
            if [ -z ${{ inputs.git-sha }} ]; then
            yq eval -i '.app.versions |= . + ["{version: '${VERSION}'}"'] ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            else
            yq eval -i '.app.versions |= . + ["{version: '${VERSION}', gitSha: '${GITSHA}'}"'] ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            fi
          yq eval -i '.app.ingress.hosts += [{"host": "'${HOST}'.${{ inputs.env }}.'${DOMAIN}'", "paths": {"- path": "/"}, "paths": {"  version": "'${VERSION}'"}}]' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
          sed -i "s/'//g" ${{ inputs.app }}/values-${{ inputs.env }}.yaml
          yq eval -i '.. style="double"' ${{ inputs.app }}/values-${{ inputs.env }}.yaml          
        else
          yq eval -i '.app.image.tag = env(VERSION)' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        fi
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config --local user.email "aeternity-bot@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit --allow-empty -m "Deploy ${HOST}.${{ inputs.env }}.${DOMAIN}"
      shell: bash
