name: Staging Deploy
description: "Staging Deploy"
inputs:
  url-prefix:
    description: "URL Prefix"
    required: true
  env:
    description: "Environment"
    required: true
  app:
    description: "Deployed Application"
    required: true
runs:
  using: "composite"
  steps:
    - id: deploy
      run: |
        sudo snap install yq
        export VERSION=${{ inputs.url-prefix }}
        export HOST=${{ inputs.url-prefix }}-${{ env.APP }}
        yq eval -i '.app.versions += [env(VERSION)'] ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        if [ ${{ inputs.env }}  != "prd" ]; then 
            yq eval -i '.app.ingress.hosts += [{"host": "'${HOST}'.${{ inputs.env }}.aepps.com", "paths": {"- path": "/"}}]' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            sed -i.bak "s/'//g" ${{ inputs.app }}/values-${{ inputs.env }}.yaml
            rm -rf ${{ inputs.app }}/values-${{ inputs.env }}.yaml.bak
            yq eval -i '.. style="double"' ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        else
            :
        fi
        cat ${{ inputs.app }}/values-${{ inputs.env }}.yaml
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git add .
        git commit -m "Deploy pr-${HOST}.${{ inputs.env }}.aepps.com"
      shell: bash
